import type { NextPage } from 'next';
import Head from 'next/head';
import { Counter } from '../slices/counter/counter';
import Todos from '../slices/todos/todos';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Next Redux toolkit</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Counter />
				{/* <Todos /> */}
			</main>
		</div>
	);
};

export default Home;
